version: '3'
services:
  spring:
    build:
      context: ../images/spring
    depends_on:
      - 'mysql'
    links:
      - mysql:db
    ports:
      - 8080:8080
    networks:
      - 'default'
    environment:
      MYSQL_ROOT_PASSWORD: root
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: amt_engine
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
     - "3306:3306"
    networks:
      - 'default'
