version: '3'
services:
  spring:
    build:
      context: ../
    links:
      - mysql:db
    ports:
      - 8080:8080
    networks:
      - 'default'
    environment:
      MYSQL_ROOT_PASSWORD: password
  mysql:
    build: ../images/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: springuser
      MYSQL_ROOT_PASSWORD: password
    ports:
     - "3306:3306"
    networks:
      - 'default'

