version: '3'
services:
  payara:
    build: ../images/payara
    environment:
     - ADMIN_PASSWORD=admin
    links:
     - mysql:db
    ports:
     - "8080:8080"
     - "4848:4848"
    links:
     - mysql:db
  mysql:
    build: ../images/mysql
    environment:
      MYSQL_DATABASE: amt_db
      MYSQL_ROOT_PASSWORD: root
    ports:
     - "3306:3306"
    networks:
      - 'default'
  phpmyadmin:
    build: ../images/phpmyadmin
    links:
     - mysql:db
    ports:
     - "6060:80"
    depends_on:
      - 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root

