swagger: '2.0'
info:
  version: '0.1.0'
  title: Engine API
  description: An API to gamify applications
host: localhost:8080
basePath: /api
schemes:
  - http
paths:
  /badges:
    post:
      description: create a badge
      operationId: createBadge
      consumes:
        - application/json
      parameters:
        - name: badge
          in: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              image:
                type: string
              type:
                type: string
              value:
                type: integer
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get the list of all badges
      operationId: getBadges
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Badge'
  /badges/{badgeId}:
    get:
      description: Gets a badge by ID.
      operationId: getBadgesById
      produces:
        - application/json
      parameters:
        - in: path
          name: badgeId
          type: long
          required: true
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/Badge'
  /pointScales:
    post:
      description: create a pointScale
      operationId: createPointScale
      consumes:
        - application/json
      parameters:
        - name: pointScale
          in: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              value:
                type: integer
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get the list of all pointScales
      operationId: getPointScales
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/PointScale'
  /pointScales/{pointScaleId}:
    get:
      description: Gets a PointScale by ID.
      operationId: getPointScaleById
      produces:
        - application/json
      parameters:
        - in: path
          name: pointScaleId
          type: long
          required: true
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/PointScale'
  /events:
    post:
      description: create an event
      operationId: createEvent
      consumes:
        - application/json
      parameters:
        - name: event
          in: body
          required: true
          schema:
            $ref: '#/definitions/Event'
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get the list of all events
      operationId: getEvents
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Event'
  /rules:
    post:
      description: create a rule
      operationId: createRule
      consumes:
        - application/json
      parameters:
        - name: rule
          in: body
          required: true
          schema:
            $ref: '#/definitions/Rule'
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get the list of all rules
      operationId: getRules
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Rule'

definitions:
  Badge:
    type: object
    properties:
      id:
        type: long
      name:
        type: string
      image:
        type: string
      type:
        type: string
      value:
        type: integer
  PointScale:
    type: object
    properties:
      id:
        type: long
      name:
        type: string
      value:
        type: integer
  Event:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      type:
        type: string
      date:
        type: string
  Rule:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      action:
        type: string