swagger: '2.0'
info:
  version: '0.1.0'
  title: Badge API
  description: An API gamify an application
host: localhost:8080
basePath: /api
schemes:
- http
paths:
  /badge:
    post:
      description: create a badge
      operationId: createBadge
      consumes:
      - application/json
      parameters:
      - name: badge
        in: body
        required: true
        schema:
          $ref: '#/definitions/Badge'
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get the list of all badges
      operationId: getBadges
      produces:
      - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Badges'
definitions:
  Badge:
    type: object
    properties:
      name:
        type: string
      image:
        type: string
      type:
        type: object
      value:
        type: object